- skeleton.sh
The short of this is that I would really like to avoid spending time doing code reviews for the command and argument parsing boilerplate that this script is going to need. I'd rather start off with a robust argument/command parsing structure that we should be able to user with little to no modification for the forseeable future and start focusing code reviews on feature work.
I have seen bash argument parsing go terribly awry and be hugely cumbersome, and I really want to avoid that here if possible. I really can't stress enough how terribly difficult it is to write good argument parsing in Bash, and I'm sure there are some people who would say my suggestion here is bad as well, though I have done my best to make it have the features we need and be as easy to read and use as possible. …
> core: suggest a new skeleton script template

- README.md
Unfortunately, we forgot to add the list of commands
we should have with our plugin. This commit updates
the doc to add commands this plugin supports.
Like, running any ceph command and restart operator.
> docs: update the Readme doc to add commands

- kubectl-rook-ceph.sh
Earlier, we have the support to read custom namespace
but there was bug that it was reading from wrong config
file. This commit fixes that bug.
Closes: https://github.com/rook/kubectl-rook-ceph/issues/24
> ceph: add support to read custom namespace

- .github/workflows/ci-for-default-ns.yaml
- .github/workflows/ci-for-diff-ns.yaml
- .github/workflows/ci.yaml
- .github/workflows/cluster-setup/action.yaml
- README.md
- kubectl-rook-ceph.sh
- tests/github-action-helper.sh
currently, the tool can't handle different namespace for operator and
cluster.
With this path, we'll have two namespaces
1. `--namespace` | `-n`: namespace of CephCluster (default: rook-ceph):
it will first read from CLI arg, if not passed then it will read from
env var `ROOK_CLUSTER_NAMESPACE` if that's empty  default to `rook-ceph`.
2. `--operator-namespace` | `-op-ns`: namespace of rook operator
(default: <namespace> i.e rook-ceph). it will first read from cli arg,
if not passed then it will read from env var `ROOK_OPERATOR_NAMESPACE`
if that's empty default to <namespace>(the one in first step) i.e
`rook-ceph`.
Closes: https://github.com/rook/kubectl-rook-ceph/issues/25
> core: support operator and cluster in different namespaces

- .github/workflows/ci-for-default-ns.yaml
- .github/workflows/ci-for-diff-ns.yaml
- README.md
- kubectl-rook-ceph.sh
- tests/github-action-helper.sh
This commit adds new command `kubectl rook-ceph health`,
which check cluster health, by looking at
1. minimum 3 mons on different nodes
2. minimum 3 osds on different nodes
3. all mons are in quorum
4. all pods state
5. pg active+clean
6. atleast one mgr pod running
Closes: #32 
> core: add health command to print cluster health

- .github/workflows/ci-for-default-ns.yaml
- .github/workflows/ci-for-diff-ns.yaml
- README.md
- kubectl-rook-ceph.sh
Debug mode will offer a special case
where the operator will don't reconcile
on the specific deployments but works
same with other controllers and deployments
Closes:	https://github.com/rook/kubectl-rook-ceph/issues/35
> core: add debug mode for mon and osd

- kubectl-rook-ceph.sh
core: default values should be set after reading flag
we should read flags before setting the default values
otherwise, if someone provides a ceph cluster namespace, the
operator namespace will still point to default rook-ceph
> core: default values should be set after reading flag

- kubectl-rook-ceph.sh
core: check node count of 3 not pod count
when checking if pods mons/osds are running on
3 three different nodes we should count uniq nodes
not unique pods see `{print $7}` instead of `{print $2}`
Closes: https://github.com/rook/kubectl-rook-ceph/issues/51
clean: use method run_ceph_command to run ceph commands
running ceph command separetly we can miss to add --connect-timeout
arg so it better to use method `run_ceph_command` to run ceph commands
with `--connect-timeout` arg. It will help exit when command is stuck.
> Remove unnecesary warning

- kubectl-rook-ceph.sh
while creating a debug pod we should add a timeout
till the deployment pod is not stopped
Closes: https://github.com/rook/kubectl-rook-ceph/issues/53
> core: add a timeout for deployment pod to stop

- kubectl-rook-ceph.sh
Closes:  https://github.com/rook/kubectl-rook-ceph/issues/44
> core: make alternate image flag unpositioned for debug mode

- README.md
- kubectl-rook-ceph.sh
core: move default values after the parsing flag
moving default flags after parsing flags and remove
redundant code.
> Remove redundant code

- README.md
- docs/ceph.md
- docs/debug.md
- docs/health.md
- docs/mons.md
- docs/operator.md
- docs/rbd.md
- docs/rook.md
This commits add docs for each command and args that the plugin supports and also, update the readme doc.
> docs: add specific docs for each command and args

- kubectl-rook-ceph.sh
In dr, if ceph status command fails for peer cluster we should continue to print rbd pool stat of local cluster. So, setting `set +e` will do the trick here.
> core: continue printing rbd pool status in failure

- docs/mons.md
Restoring the mon quorum can be a risky operation and the admin may want to see example output to give more confidence that they will be prompted to continue after they are sure they want to restore the quorum.
> docs: Add example output for restoring quorum

- docs/mons.md
The restore quorum doc had some extra output and also need consistent formatting between the blocks of
output.
My bad for not viewing the rendered output before merging #65.
> docs: Fix rendering of restore mons doc

- .github/workflows/ci-for-default-ns.yaml
- .github/workflows/ci-for-diff-ns.yaml
- kubectl-rook-ceph.sh
- tests/github-action-helper.sh
Instead of random sleep time, added timeout
so we will wait till the pods get started
Closes: https://github.com/rook/kubectl-rook-ceph/issues/42
> ci: added timeout instead of sleep commands

- .github/workflows/collect-logs/action.yaml
- .github/workflows/go-test.yaml
- cmd/commands/ceph.go
- cmd/commands/mons.go
- cmd/commands/rbd.go
- cmd/commands/rook.go
- kubectl-rook-ceph.sh
- pkg/debug/start_debug.go
- pkg/debug/stop_debug.go
- pkg/exec/exec.go
- pkg/k8sutil/operator.go
- pkg/mons/restore_quorum.go
- pkg/rook/purge_osd.go
- tests/collect-logs.sh
- tests/github-action-helper.sh
core: add restore mon quorum in go
this commits add a go command for
restore the mon quorum from single
good mon. In the background we,
scale down the operator first, and run some
ceph commands like remove bad mans from
mon map, extracting/injecting monmap.
And, in the end, we scale up the operator which
bring back the mon quorum.
> core: add restore mon quorum in go

- .github/workflows/go-test.yaml
- cmd/commands/health.go
- pkg/health/health.go
core: add health command in go
These changes are on top of the mon quorum pr, so check the last commit only. Thanks!
command
`kubectl rook-ceph health`
output
```
Info:  Checking if at least three mon pods are running on different nodes
Warning: At least three mon pods should running on different nodesrook-ceph-mon-a-655fbb547-7fbbn        Running         rook-ceph       minikube
rook-ceph-mon-b-6f74686789-bl5lj         Running         rook-ceph       minikube
rook-ceph-mon-c-7676c5485-bbg2v          Running         rook-ceph       minikube
Info:  Checking mon quorum and ceph health details
Info:  Checking if at least three osd pods are running on different nodes
Warning: At least three osd pods should running on different …
```
> core: add health command in go

- cmd/commands/root.go
- pkg/debug/start_debug.go
- pkg/debug/stop_debug.go
- pkg/dr/health.go
- pkg/exec/exec.go
- pkg/health/health.go
- pkg/k8sutil/context.go
- pkg/k8sutil/operator.go
- pkg/mons/mon_endpoints.go
- pkg/mons/restore_quorum.go
- pkg/rook/purge_osd.go
core: don't use context.ToDo everywhere
using context.ToDo always is not a good practice.
So, now having a central place of context which
all methods will use.
> core: don't use context.ToDo everywhere

- pkg/dr/health.go
adding log when dr is not configured and
also adding the color logging which was missed for dr command.
fixes: #100
> dr: add log when dr is not configured

- pkg/health/health.go
prepare pod or pod which are in succeeded state were showing in warning instead of info. Now, succeeded is considered as running state for log.
fixes: #103
> health: succeeded pod should not be in warning

- pkg/logging/log.go
- pkg/rook/status.go
status: remove extra empty line logging
changing Info() method to print `Info` and
logs with new line only when output is not empty
otherwise it will print `Info:` with empty line.
fixes: #102
> status: remove extra empty line logging

- cmd/commands/ceph.go
- cmd/commands/debug.go
- cmd/commands/dr_health.go
- cmd/commands/health.go
- cmd/commands/mons.go
- cmd/commands/operator.go
- cmd/commands/rbd.go
- cmd/commands/rook.go
- cmd/commands/root.go
- pkg/debug/start_debug.go
- pkg/debug/stop_debug.go
- pkg/dr/health.go
- pkg/exec/exec.go
- pkg/health/health.go
- pkg/k8sutil/context.go
- pkg/k8sutil/operator.go
- pkg/mons/mon_endpoints.go
- pkg/mons/mon_endpoints_test.go
- pkg/mons/restore_quorum.go
- pkg/rook/purge_osd.go
Documentation in context.Context states never to embed a context.Context in a struct. It should always be passed to functions and methods, ideally as the first parameter. Kubernetes' Go API follows this syntax, and since it is much easier to fix the issue in kubectl-rook-ceph compared to in rook/rook, we should do so.
The old k8sutil.Context has been renamed to k8sutil.Clientsets to reflect its new purpose.
> Use recommended context.Context passing

- cmd/commands/ceph.go
- cmd/commands/root.go
- pkg/k8sutil/operator.go
Namespace flags should be parsed by the parent command and not by child
commands. This poses a particular problem for the 'ceph' and 'rbd'
commands, as they normally have flag parsing disabled. The parent
command should use the cobra.Command option 'TraverseChildren' in order
to parse parent args before parsing child commands.
This is built on top of #112
> Fix parsing for namespace flags

- .github/workflows/go-test.yaml
- cmd/commands/ceph.go
- cmd/commands/rbd.go
- cmd/commands/rook.go
- pkg/dr/health.go
- pkg/exec/exec.go
- pkg/health/health.go
- pkg/mons/restore_quorum.go
- pkg/rook/purge_osd.go
with earlier approach purging an OSD was hanging.
since, with bash implementation, it was passing so, this commit change the way osd removal command runs. Earlier, we were creating connection between the operator and then running the command now we are using os/exec package.
fixes: #98
> core: fix osd hang during purge-osd

- cmd/commands/ceph.go
- cmd/commands/debug.go
- cmd/commands/dr_health.go
- cmd/commands/health.go
- cmd/commands/mons.go
- cmd/commands/operator.go
- cmd/commands/rbd.go
- cmd/commands/rook.go
- cmd/commands/root.go
core: validate namespace before proceeding
we should validate if namespaces exist or not
before running any commands.
core: throw a warning when an unsupported version of rook is used
this, commit throws warning when unsupported version of rook
is used for example if rook version contain alpha or beta,
it will throw warning.
fixes: https://github.com/rook/kubectl-rook-ceph/issues/110
> core: validate namespace before proceeding

- cmd/commands/root.go
- cmd/commands/root_test.go
- pkg/exec/exec.go
core: make rook version more readable
during pre-validation check, rook version was
printed in multiple lines with golang version
which was making it difficult to read. Now, it
prints in one single like with the golang version.
core: print version info only once
there was extra `fmt.Print()` in method `RunCommandInOperatorPod`
due to which command output was printed two times.
fixes: #118
> core: make rook version more readable

- pkg/exec/exec.go
there is no need to enabling stdin while
connecting with stream to rum the command inside
the pods. So, removing the `Stdin` field which makes it false.
fixes: #119 
> core: fix error when reading stdin

- pkg/debug/start_debug.go
The output describe debug pod availability needed to be clarified
> logs: Fix wording for debug pod

- cmd/commands/root.go
- pkg/logging/log.go
core: comment unnecessary namespace for now
fixes: #118
> core: comment unnecessary namespace for now

- .github/workflows/release.yaml
- .goreleaser.yaml
adding goreleaser to help in building the
project with different os and architecture.
Later, we'll use the artifact create from this
ci to pass it to krew release yaml.
> ci: add goreleaser to build the project

- .krew.yaml
updating the krew yaml to reflect the changes are coming from go migration. This krew file is used as configuration file for krew ci krew-release-bot to create the pr in krew index repo.
Signed-off-by: subhamkrai srai@redhat.com
> krew: update krew yaml to reflect change to go

- .github/workflows/go-test.yaml
- cmd/commands/root.go
- pkg/debug/start_debug.go
- pkg/mons/restore_quorum.go
namespace: namespace flags are not working
cluster namespace and operator namespace needs
better handling. It was throwing an error and was exited
when namespace args are passed.
Now, the default cluster ns is rook-ceph, and for
operator it is empty but we check later in the code
that if CephClusterNamespace != "" && OperatorNamespace == ""
then assign the cluster ns to operator ns.
ci: add CI to test the plugin in different namespace
fixes: #129
> namespace: namespace flags are not working

- cmd/commands/rook.go
- pkg/rook/status.go
In some environment jq is not present by default
and the tool will through error. We are adding
flag `json` to print the rook status output in
json format otherwise it will simple.
example: without json.
```
./bin/kubectl-rook-ceph rook status cephcluster
Info: NAME         DATADIRHOSTPATH   MONCOUNT   AGE   PHASE   MESSAGE                        HEALTH        EXTERNAL   FSID
my-cluster   /var/lib/rook     1          15h   Ready   Cluster created successfully   HEALTH_WARN              cd10c270-c912-4e67-ab86-b4161df498d1
```
with json:
```
./bin/kubectl-rook-ceph rook status cephcluster --json
Info: {
"apiVersion": "v1",
"items": [
{
"apiVersion": "ceph.rook.io/v1",
"kind": "CephCluster",
"metadata": {
...
...
```
Fixes: #132
> remove-jq: add flag json to removing uses of jq tool

- cmd/commands/root.go
some clusters may have some kind of kubectl authenticator example 'OIDC', `gcb`, etc. So adding the auth pkg will help.
Fixes: #134
> add-auth: add auth plugin package

- .github/workflows/go-test.yaml
- cmd/commands/root.go
we missed adding `--context` flag when migrating
to golang. Adding the flag back.
fixes: #136
> flag: add context flag to switch between clusters

- .github/workflows/go-test.yaml
- tests/github-action-helper.sh
ci: update script to get right device filter
currently, deviceFilter was getting `/dev/sdb` instead
of `sdb` due to which osd is not getting created. Also,
modified few commands to clean disk before using.
ci: update tmate to disable limit access
> ci: update script to get right device filter

- .github/dependabot.yaml
ci: add dependabot to update dependencies
this commit adds dependabot to update dependencies
which we miss/forget to update untill some issues
> ci: add dependabot to update dependencies

- pkg/logging/log.go
Core: redirect log messages to stderr
The PR redirects the log messages to stderr so that the 
json output from some commands can be parsed with eg jq.
> Redirect logs to stderr.

- cmd/commands/ceph.go
- cmd/commands/debug.go
- cmd/commands/dr_health.go
- cmd/commands/health.go
- cmd/commands/operator.go
- cmd/commands/rbd.go
- cmd/commands/rook.go
- cmd/commands/root.go
we should not be waiting or doing any operation realted to operator when it is not really required. Also, in some cases user may have intentionally scale down the operator. That's why we should skip doing operator operation when not required.
> command: skip operator pod check when not required

- cmd/commands/rook.go
It was unclear in the help section of purge-osd
on how to remove multiple osd at once. So adding
an example command to remove multiple osd.
Fixes: #181
> usages: Clear how to use purge-osd command

- pkg/mons/restore_quorum.go
somehow log to ask user to press enter to
start the operator and continue starting
mon quorum was missing, adding now. It was
mentioned in the doc but missing the command.
> mons: adding missing info to start operator

- Makefile
Signed-off-by: Michael Adam <obnox@samba.org>
`make clean` was broken because the rm command pointed to a non-existing file location.
This fixes this by using the correct path.
> build: fix `make clean`

- docs/health.md
it should be requires instead reuires, due to
this codespell was failing.
> docs: codespell ci failing due incorrect spell

- .github/workflows/go-test.yaml
- README.md
- cmd/commands/restore.go
- cmd/main.go
- docs/crd.md
- pkg/debug/start_debug.go
- pkg/debug/stop_debug.go
- pkg/exec/bash.go
- pkg/k8sutil/k8sutil.go
- pkg/mons/restore_quorum.go
- pkg/restore/crd.go
- tests/github-action-helper.sh
with these changes we'll be able to restore any
crd which stuck deletion due some dependencies
after after accidental deletion.
example:
kubectl rook-ceph -n <ns> restore <cr> <cr_name>
fixes: #68
> restore: restore crd after accidental deletion

- tests/github-action-helper.sh
github ci runner is allocating both 14 and 64 Gb disks to the setup. CI currently hard codes the lsblk with a 14G filter. This PR updates the filter to use either 14G or 64G disks.
Resolves #
**Checklist:**
> ci: filter both 14 and 64 disks in CI

- .github/workflows/go-test.yaml
- cmd/commands/subvolume.go
- cmd/main.go
- docs/subvolume.md
- pkg/filesystem/subvolume.go
- tests/github-action-helper.sh
1. Includes command to list and delete the stale subvolume
2. documentation to understand the usage of the command
> Add command to clean the stale subvolume

- cmd/commands/ceph.go
- cmd/commands/debug.go
- cmd/commands/dr_health.go
- cmd/commands/health.go
- cmd/commands/mons.go
- cmd/commands/operator.go
- cmd/commands/rbd.go
- cmd/commands/restore.go
- cmd/commands/rook.go
- cmd/commands/root.go
- cmd/commands/subvolume.go
Let's use cobra `PreRun`,`PreRunE`, `PersistentPreRun` and `PersistentPreRun` feature to do pre-validation checks. Also, refactor the code.
**Checklist:**
Resolves #
**Checklist:**
> clean: use cobra built-in feature for pre-validation

- .github/workflows/go-test.yaml
- cmd/commands/root.go
- docs/crd.md
- pkg/crds/crds.go
- pkg/k8sutil/dynamic.go
- pkg/k8sutil/interface.go
- pkg/k8sutil/mocks.go
- pkg/restore/crd.go
currently, we are directly using `kubectl` command to get crds, crd name and also for other ops. Since, we now have code to get k8s resource using dynamic api, let's use that instead of `kubectl` command.
One thing to notice, now it more restrict when passing the ceph crd
types. For example, earlier `cephcluster` used to work now we need to be
specific `cephclusters`.
**Checklist:**
> restore-crd: use dynamic api to get k8s resource

- tests/github-action-helper.sh
the disk size in the github action machine has
increased from 64G to 75G.
Resolves #
**Checklist:**
> ci: disk in github action increased to 75G from 64G

- cmd/commands/rook.go
- docs/rook.md
- go.mod
- pkg/crds/crds.go
- pkg/rook/status.go
to get crd resources let's start using dynamic api
of kubernetes instead of using `kubectl` cli directly.
It make it platform independent wether it is `kubectl`
kubernetes or `oc` openshift.
Note: it changes how the command output used to be.
**Checklist:**
> status: using dynamic api instead of kubectl

- pkg/filesystem/subvolume.go
It seems the getfilesystem was always returning an empty struct. This commit returns the actaul
filesystem struct.
> csi: return filesystem details

- .github/workflows/go-test.yaml
- cmd/commands/subvolume.go
- docs/subvolume.md
- pkg/filesystem/subvolume.go
This PR introduces the following enhancement to the stale subvolume cleanup process:
* Allow to delete the stale subvolumes that have snapshots with retain-snapshot feature
* Correct the order of arguments passed while deleting the subvolume
* Allow users to delete only one subvolume at a time.
> Allow to delete subvolume with retain-snapshot feature

- docs/mons.md
- pkg/exec/exec.go
- pkg/mons/restore_quorum.go
let's validate the mon id passed by user based on which
quourm is restored. We don't want to restore quorum which is
not either 'leader' or 'peon'.
Resolves #
**Checklist:**
> mon: fetch good mon from socket command

- .github/workflows/go-test.yaml
- .github/workflows/release.yaml
- .github/workflows/set-up-go/action.yaml
created a composite yaml for setting up go versio
that will be use for CI and releaser yaml. The releaser ci is failing https://github.com/rook/kubectl-rook-ceph/actions/runs/8003450560/job/21858788476 with error
```
⨯ release failed after 0s                  error=hook failed: shell: 'go mod tidy': exit status 1: go: go.mod file indicates go 1.21, but maximum version supported by tidy is 1.20
```
hopefull after this, releaser ci will be happy.
Resolves #
**Checklist:**
> ci: update runner go version to 1.21

- .github/workflows/go-test.yaml
until we fix the rbd hang command issue let's skip this in CI so that other PR's CI goes to running.
Resolves #
**Checklist:**
> ci: skip rbd command in ci

- .github/workflows/go-test.yaml
- docs/subvolume.md
- pkg/exec/exec.go
- pkg/filesystem/subvolume.go
- pkg/filesystem/subvolume_test.go
- tests/github-action-helper.sh
Remove the omap object for the given subvolume.
> clean cephFS omap details

- pkg/mons/restore_quorum.go
since ceph reef, monMapArg `--public-bind-addr` is not required anymore.
Resolves #185 
**Checklist:**
> mon: remove unnecessary arg `public bind addr`

- .github/workflows/go-test.yaml
- README.md
- cmd/commands/rados.go
- cmd/main.go
- docs/rados.md
Add rados command option to kubectl-rook-ceph [Krew](https://github.com/kubernetes-sigs/krew) plugin.
Resolves #268 
**Checklist:**
Procedure:
1.Create minikube on my local machine:
minikube start --disk-size=10g --extra-disks=1 --driver kvm2
2.Create Opertaor via conf files from rook repository https://github.com/rook/rook
$ cd deploy/examples/
$ kubectl create -f crds.yaml -f common.yaml -f operator.yaml
$ kubectl get pods -n rook-ceph
NAME                                 READY   STATUS    RESTARTS   AGE
rook-ceph-operator-757cdc49bb-qqffn   1/1     Running   0          89s
3.Create cluster-test:
$ cd deploy/examples/
$ kubectl create -f cluster-test.yaml 
configmap/rook-config-override created …
> core: add rados commands options

- .github/dependabot.yaml
update dependencies in a group so that
the k8s api doesn't throws error and
all the deps are updated in single PR.
Resolves #
**Checklist:**
> ci: update dependencies in a group

- tests/github-action-helper.sh
PVC.spec.volumeName is empty if it's not bound to any PV. This problem can be avoided by getting the name
after verifying PVC to be bound.
ref. https://github.com/rook/kubectl-rook-ceph/actions/runs/8908445423/job/24464082185?pr=229#step:15:128
```
+ kubectl get pvc cephfs-pvc-retain
NAME                STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS         AGE
cephfs-pvc-retain   Pending                                      rook-cephfs-retain   0s
++ kubectl get pvc cephfs-pvc-retain '-o=jsonpath={.spec.volumeName}'
+ : ''
+ wait_for_pvc_to_be_bound_state_default
```
**Checklist:**
> core: set pv name correctly on subvolume test

- .github/workflows/go-test.yaml
- cmd/commands/flatten_rbd_pvc.go
- cmd/main.go
- docs/flatten-rbd-pvc.md
- pkg/flatten-rbd-pvc/flatten_rbd_pvc.go
- tests/github-action-helper.sh
- Flatten an RBD image corrensponding to the target PVC
- Remove the corresponding temporary RBD image
Resolves #222
**Checklist:**
> core: add flatten-rbd-pvc command

- .github/workflows/go-test.yaml
- README.md
- cmd/commands/radosgw.go
- cmd/main.go
- docs/radosgw-admin.md
- pkg/exec/exec.go
adding support for 'radosgw-admin' command in the cli tool and also adding docs and ci.
**Issue resolved by this Pull Request:**
Resolves #253 
**Checklist:**
> core: adding 'radosgw-admin' command support

- pkg/filesystem/subvolume.go
this commit deletes the nfs config entry for
the stale subvolume
Resolves: #272
> delete nfs config for stale subvolume

- pkg/k8sutil/k8sutil.go
To prevent pods in the `Completed` phase to show up in the list pulled by `WaitForPodToRun` (which resulted in an indefinitely hang), add a filter to only return pods in the `Running` phase.
**Issue resolved by this Pull Request:**
Resolves #304 
**Checklist:**
> core: Add status.phase=Running filter to WaitForPodToRun

- .github/workflows/cluster-setup/action.yaml
- .github/workflows/go-test-config/action.yaml
- .github/workflows/go-test.yaml
- tests/github-action-helper.sh
Remove duplicated description between the default configuration and the custom namespace configuration.
**Checklist:**
> test: simplify go-test

- pkg/filesystem/subvolume.go
- pkg/filesystem/subvolume_test.go
In case of ROX pvc, the subvolume name is different and is not listed in the backend as it is just a shallow volume and it links to the source path.
incase the source volume is delete the subvolme will be shown stale, but actually that is being used by the ROX pvc.
Soinstead getting the subvolumename to look for stale subvolumes, it is better to retrive the name from the subvolumepath.
> csi: look for subvolumepath instead of subvolumename

- pkg/filesystem/subvolume.go
Incase any pvc is in pending state and the backend subvolume is create, it will be counted as stale.
this commit adds the error check to make sure user doesn't delete the subvolume if it the pvc is in
pending state.
> csi: add check for pending clone

- pkg/filesystem/subvolume.go
this commit adds an extra check to check the drivername.
> csi: add check to include only cephfs subvolumes

- .github/workflows/cluster-setup/action.yaml
- tests/github-action-helper.sh
this commit upgrade the minikube, k8s, crictl versions in CI and also fix permission error in the github runner.
**Checklist:**
> ci: fix ci permission issue with minikube start

- .github/workflows/go-test-config/action.yaml
- pkg/crds/crds.go
- pkg/k8sutil/k8sutil.go
The cleanup policy was not allowed to take effect during the cluster cleanup. The finalizer was immediately be removed instead of remaining until the operator has a chance to handle the cleanup policy and internally remove the finalizer. Now the cleanup policy is allowed to be applied and the cleanup job(s) will be started to cleanup the host path and disks from OSDs.
**Checklist:**
> clean: Ensure cephcluster cleanup job runs

- cmd/commands/rook.go
- docs/rook.md
- pkg/rook/purge_osd.go
Updating the command pre run to parse
the comma separated list of OSD IDs
**Checklist:**
> core: fix purge_osd command for multiple OSD IDs

- tests/github-action-helper.sh
this pr introduces a new test to verify the  `rbd ls`
command functionality when working with rados namespaces.
the test ensures that rbd images are correctly listed
```
$ ./bin/kubectl-rook-ceph rbd ls
poolName            imageName                                     namespace    
--------            ---------                                     ---------    
blockpool-rados-ns  csi-vol-465d5545-b621-4adb-afd6-fd548dbd0062  namespace-a  
blockpool-rados-ns  ---                                           namespace-b  
replicapool         ---                                           ---  
```
when namespaces are configured.
**Checklist:**
> csi: add test for `rbd ls` with rados namespace

- pkg/rbd/rbd.go
#356
Previously, the code only filtered out "builtin-mgr", but other builtin pools still caused rbd ls to fail. This fix updates the condition to exclude all pools containing "builtin", preventing errors when listing RBD images.
**Checklist:**
> csi: fix rbd listing failure by correctly filtering builtin block pools

- cmd/commands/restore.go
- pkg/restore/crd.go
Refactored the RestoreCrd function to accept groupName and
versionResource as parameters instead of relying on the hardcoded
constants crds.CephRookIoGroup and crds.CephRookResourcesVersion.
This improves flexibility and allows the function to handle
different CRDs dynamically.
**Checklist:**
> maintenance: remove hardcoded crd constants in restoreCrd

- cmd/commands/root.go
The root command is executed from main() directly so Execute is unused. Its only effect seems to be confusing new contributor.
**Checklist:**
> core: remove unused Execute()

- .github/workflows/codespell.yaml
- .github/workflows/commitlint.yaml
- .github/workflows/go-test.yaml
- .github/workflows/release.yaml
- .github/workflows/shell-check.yaml
ubuntu-20.04 is obsolete now, let's use ubuntu-22.04 in ci
**Issue resolved by this Pull Request:**
Resolves #369 
**Checklist:**
> ci: update ubuntu version to 22.04

- pkg/mons/mon_endpoints.go
- pkg/mons/mon_endpoints_test.go
- pkg/mons/restore_quorum.go
This PR fixes an issue with the `kubectl-ceph-rook` plugin when working with Ceph clusters configured with IPv6 addresses. The current implementation of the `getMonDetails()` function fails to correctly parse IPv6 monitor endpoints, causing commands like `mons restore-quorum` to fail.
When running `kubectl rook-ceph mons restore-quorum` with IPv6 monitor addresses, the command fails with an error:
```
Info: mon=a, endpoints=[2a02:5501:31:c0a::3]:6789
Info: mon=b, endpoints=[2a02:5501:31:c0a::4]:6789
...
Info: Restoring mon quorum to mon b [2a02
...
parse error setting 'public_addr' to '[2a02'
too many arguments: [--setuser-match-path=/var/lib/ceph/mon/ceph-b/store.db]
Error: failed to run command. failed to run command. command terminated with exit code 1
%!(EXTRA string=failed to extract …
```
> kubectl-ceph-rook: Fix IPv6 address handling in monitor endpoint parsing

- cmd/commands/restore.go
- pkg/restore/crd.go
This PR extends the `RestoreCrd` functionality to support restoring additional third-party CRs 
- Adds a `CustomResource` struct to pass a list of CRs to clean up ownerReferences
- Enhances `removeOwnerRefOfUID` to work with dynamically provided CRs
- Makes the operator name configurable to support tearing down and restarting a different operator (not just rook-ceph-operator)
This change improves flexibility in disaster recovery scenarios 
**Checklist:**
> mon: add support for restoring arbitrary CRs while the Rook resources are being deleted

- pkg/mons/mon_endpoints.go
- pkg/mons/mon_endpoints_test.go
- pkg/mons/restore_quorum.go
This PR fixes IPv6 monitor endpoint handling in the kubectl-rook-ceph plugin. The plugin was incorrectly parsing and displaying IPv6 addresses, causing issues with both monitor status display and quorum restoration operations.
When running `kubectl rook-ceph mons`, IPv6 addresses were corrupted:
**Expected output:**
```
[2a02:5501:31:c0a::3]:6789,[2a02:5501:31:c0a::4]:6789
```
**Actual output:**
```
202:5501:31:0::3:6789,202:5501:31:0::4:6789
```
**Root cause:** The regex `[^0-9,.:]` in `GetMonEndpoint()` was removing hexadecimal letters (`a`, `c`), square brackets (`[]`), and equals signs (`=`) from IPv6 addresses.
When running `kubectl rook-ceph restore-quorum`, IPv6 addresses were saved incorrectly to ConfigMap:
**Expected ConfigMap data:**
```yaml
data: i=[2a02:5501:31:c0a::4]:6789 …
```
> kubectl-ceph-rook: fix correct IPv6 address parsing in GetMonEndpoint

- cmd/commands/subvolume.go
subvolume command has some known issue let's hide
that until we have fix for the know issue.
**Checklist:**
> subvolume: hide subvolume delete command for now
