.github/workflows/ci.yaml, .github/workflows/shell-check.yaml, README.md, kubectl-rook-ceph.sh, tests/github-action-helper.sh
This commit adds inital code with
ceph command supported.
Closes: #2 
=> core: add initial code

.krew.yaml
updating the manifest file according to what we have
in krew side. Last time we faced issues and fixed in
krew repo but it require fix here too.
=> manifest: update the manifest file according

kubectl-rook-ceph.sh, tests/github-action-helper.sh
this commit format all the shell the script
according the `shell-format` extention in vscode.
=> core: format script using `shell-format` in vscode

kubectl-rook-ceph.sh
Add KUBECTL_NS_OPERATOR and KUBECTL_NS_CLUSTER functions to replace
repeated calls of `TOP_LEVEL_COMMAND --namespace "${ROOK_*_NAMESPACE}"`.
Use all caps for the function names so they stand out more clearly. When
using `kubectl_ns_operator some-command`, it isn't as clear that it is a
special type of call.
Signed-off-by: Blaine Gardner <blaine.gardner@redhat.com>
=> Add reusable functions for kubectl in namespaces

README.md
=> docs: fix doc comment

.github/workflows/ci-for-default-ns.yaml, .github/workflows/cluster-setup/action.yaml, .github/workflows/codespell.yaml
=> ci: add codespell in ci

.github/workflows/ci-for-default-ns.yaml, .github/workflows/ci-for-diff-ns.yaml
=> ci: add a timeout time for tmate session

.github/workflows/ci-for-default-ns.yaml, .github/workflows/ci-for-diff-ns.yaml, .github/workflows/release.yaml, .github/workflows/shell-check.yaml
=> ci: update ubuntu to 20.04

.github/workflows/go-test.yaml, cmd/commands/operator.go, cmd/main.go, pkg/k8sutil/operator.go
=> core: add operator commands in go

.github/workflows/go-test.yaml, cmd/commands/ceph.go, cmd/commands/mons.go, cmd/commands/rbd.go, cmd/commands/rook.go, pkg/exec/bash.go, pkg/exec/exec.go, pkg/k8sutil/operator.go, pkg/mons/mon_endpoints.go, pkg/mons/mon_endpoints_test.go, pkg/rook/purge_osd.go, pkg/rook/status.go
core: add command rook and its sub-command
=> core: add command rook and its sub-command

.github/workflows/go-test.yaml, cmd/commands/debug.go, cmd/main.go, pkg/debug/start_debug.go, pkg/debug/stop_debug.go
=> core: add start/stop debug command

cmd/commands/debug.go, cmd/commands/operator.go, cmd/commands/rook.go, cmd/commands/root.go, cmd/main.go, go.mod, go.sum, pkg/debug/start_debug.go, pkg/debug/stop_debug.go, pkg/exec/bash.go, pkg/exec/exec.go, pkg/health/health.go, pkg/k8sutil/operator.go, pkg/logging/log.go, pkg/mons/mon_endpoints.go, pkg/mons/restore_quorum.go, pkg/rook/purge_osd.go, pkg/rook/status.go
core: update logging, remove unused var
This commits brings bash color logging in GoLang.
Also, it has little cleanup with unused variable/function
and improve loggng.
=> core: update logging, remove unused var

pkg/debug/start_debug.go, pkg/debug/stop_debug.go, pkg/k8sutil/operator.go, pkg/logging/log.go
adding logs to get debug start/stop the confirmation
and also, fixing minor bugs.
fixes: #99
=> core: add some debug logging and fix small bugs

.github/workflows/go-test.yaml, pkg/mons/restore_quorum.go
validating user input `yes-really-restore` and also fixing a couple of typos.
fixes: #97
=> mons: improve mon restore quorum

.github/workflows/go-test.yaml, go.mod
core: update golang version to 1.20
=> core: update golang version to 1.20

README.md
This wixes what I think is a typo in the  readme
=> docs: fix a typo in the README

docs/rook.md
just some rewording that occurred to me when reading the docs
=> docs: improve wording in rook command documentation

.github/workflows/cluster-setup/action.yaml, tests/github-action-helper.sh
=> ci: update kubernetes version to 1.28

go.mod, go.sum
updating go version from 1.20 to 1.21
Resolves #
**Checklist:**
=> build: update go version to 1.21

cmd/commands/debug.go, cmd/commands/dr_health.go, cmd/commands/mons.go, cmd/commands/operator.go, cmd/commands/restore.go, cmd/commands/rook.go, cmd/commands/root.go, cmd/commands/subvolume.go
adding small enhancement, adding examples for required commands, using small caps for error logging.
Resolves #
**Checklist:**
=> enhancement: add sample example in the commands

pkg/filesystem/subvolume.go
!-- Please take a look at our Contributing documentation before submitting a Pull Request!
https://rook.io/docs/rook/latest/Contributing/development-flow/
Thank you for contributing to Rook! -->
There can be PV in the cluster that are not CSI based and for those PVs we need to check CSI in PV as its a pointer object.
Resolves #
**Checklist:**
=> csi: add check for CSI PV

cmd/commands/destroy_cluster.go, pkg/mons/restore_quorum.go, pkg/restore/crd.go
when taking user input to expand full quorum that
prompt was not working as expected. We had same copied value of got so got==want was always working as true..
Resolves #
**Checklist:**
=> enhancement: improve prompt input from cli

cmd/commands/ceph.go, cmd/commands/rbd.go, cmd/commands/rook.go, cmd/commands/root.go, pkg/dr/health.go, pkg/exec/exec.go, pkg/filesystem/subvolume.go, pkg/health/health.go, pkg/mons/restore_quorum.go, pkg/rook/purge_osd.go
- handle errors in callers as possible
- enrich error messages
**Checklist:**
=> core: enhance error handling

.commitlintrc.json, tests/github-action-helper.sh
removing krew installation as it was not used anywhere.
Resolves #
**Checklist:**
=> clean: remove krew installation

pkg/k8sutil/k8sutil.go
check for empty field 'data' in configmap before updating otherwise it will through nil pointer error.
Resolves #
**Checklist:**
=> operator: check for empty configmap before update

.github/workflows/go-test.yaml, tests/github-action-helper.sh
ci: fix ci issues related to osd
due to some flaky osd pod was not coming up
and ci tests were failing. Also, improving some
ci related code.
Resolves #249 
**Checklist:**
=> ci: fix ci issues related to osd

pkg/filesystem/subvolume.go
This commit adds extra setup that if required for
subvolume cleanup incase of external mode
=> csi: add setup for external mode for subvolume cleanup

pkg/filesystem/subvolume.go
this commit enhances the error message to
give detail info to the users.
=> csi: enhance error messages

.github/workflows/go-test.yaml, README.md, cmd/commands/ceph.go, cmd/commands/ceph_test.go, docs/ceph.md, pkg/exec/exec.go
adding `ceph daemon *` command support
Resolves #208
=> core: add ceph daemon command support

.github/PULL_REQUEST_TEMPLATE.md
updating pr templatet to match the rook's pr template
Resolves #
**Checklist:**
=> ci: update pr template to match rook's pr template

tests/github-action-helper.sh
ci is failing when waiting for blockpoolradosnamespace due to timeout but when checked logs phase was ready.
**Checklist:**
=> ci: increase wait timeout for blockready state

pkg/filesystem/subvolume.go
subvolume ls should not fail if volumesnapshotcontents resource does not exist, instead log a warning and continue
Fixes: #388 
**Checklist:**
=> csi: skip failure when volumesnapshotcontents crd is missing
